Fixes audio rerouting problem after reconnect Bluetooth headset
ubports/pulseaudio-packaging pull request #5
Opened 2020-09-23 18:24 UTC by peat-psuwit

This is fixed by backporting a series of patches from upstream relating
to default sink handling. Fixes ubports/ubuntu-touch#1045.

2020-09-23 21:04 UTC, UniversalSuperBox requested changes
Nearly there!

My audio playback tests guided by https://wiki.ubuntu.com/Process/Merges/TestPlan/pulseaudio passed with flying colors. Audio playback from the system, alarms, and notifications went well.

Importantly, reconnecting my Bluetooth headphones more than once and resuming audio **worked**! I've missed this for so long!

This applies to the Fairphone 2, OnePlus One, Nexus 5, and Xperia X.

However, it appears this may cause problems with audio recording. When plugging in a pair of headphones with a microphone before installing `pulseaudio-packaging 5`, I get the "Microphone" slider in the sound indicator. I can use this to raise and lower the recording volume, made clear by recording in the Recorder app in the open-store.

Once this PR is installed, plugging in headphones no longer causes the microphone slider to appear in the sound indicator.

2020-09-23 21:19 UTC, UniversalSuperBox commented
I should note that I discovered https://github.com/ubports/ubuntu-touch/issues/1569 while testing this, but it is not a regression caused by this PR.

2020-09-24 15:01 UTC, peat-psuwit commented
Well, I made a stupid mistake: I put `core->default_sink` into `def_source` variable. :facepalm:

So, in the server info command, I made that mistake, resulting in PA putting the default sink name into the default source field. The indicator-sound then tries to look up a source with a non-existent name, thus cannot determine if the headset port is in use.

This should be fixed now; hopefully, I don't make another mistake. You may want to pay attention to the patches marked `Origin: backport`, as that means I modify the patch in some way.

2020-09-30 17:29 UTC, UniversalSuperBox approved these changes
I've tested this successfully on Nexus 5, Nexus 7, Nexus 4, Fairphone 2, OnePlus One, PinePhone, Volla Phone, and Xperia X. Audio always moves over to the most relevant sink when the time comes.

The issue with the microphone icon in the sound indicator is now done.

2020-09-30 17:29 UTC, merged